# Generated by Django 5.1 on 2024-08-29 21:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='ChatMessage',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='communicati_convers_d606fd_idx',
            old_name='communicati_convers_f41ec9_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='communicati_sender__e80e75_idx',
            old_name='communicati_sender__822f5c_idx',
        ),
    ]
