# Generated by Django 5.1 on 2024-08-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('planting_months_from', models.PositiveIntegerField()),
                ('planting_months_to', models.PositiveIntegerField()),
                ('flowering_months_from', models.PositiveIntegerField()),
                ('flowering_months_to', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('rose', 'Rose'), ('flower', 'Flower'), ('tree', 'Tree'), ('bush', 'Bush')], default='unknown', max_length=100)),
                ('sun_preference', models.CharField(choices=[('full_sun', 'Full Sun'), ('partly', 'Partly'), ('full_shade', 'Full Shade')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('in_stock', models.PositiveIntegerField()),
            ],
        ),
    ]
