# Generated by Django 5.1 on 2024-08-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='height_from',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum height in meters', max_digits=5),
        ),
        migrations.AddField(
            model_name='seed',
            name='height_to',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum height in meters', max_digits=5),
        ),
    ]
