# Generated by Django 5.1 on 2024-08-17 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0003_seed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
