# Generated by Django 5.1 on 2024-08-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0004_seed_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seed',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
