# Generated by Django 5.1 on 2024-09-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0005_seed_deleted_seed_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='seed',
            name='is_in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
