# Generated by Django 5.1.4 on 2025-02-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0006_remove_seed_in_stock_seed_is_in_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='in_stock_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
