# Generated by Django 5.1 on 2024-10-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_accounts', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_self',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
