# Generated by Django 5.1 on 2024-10-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_accounts', '0004_userprofile_about_self'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receives_newsletter',
            field=models.BooleanField(default=False),
        ),
    ]
