# Generated by Django 5.1 on 2024-11-06 20:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_accounts', '0007_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='/static/images/user-icon.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
