# Generated by Django 5.1 on 2024-09-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_deleted_cart_last_modified_cartitem_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
