# Generated by Django 5.1 on 2024-09-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_rename_total_price_cart_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_total_price',
        ),
    ]
